name: Build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: 14.18.2

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - uses: pnpm/action-setup@v2
              with:
                  version: 7.13.1

            - name: Build
              run: |
                  pnpm i
                  pnpm run build
